on:
  workflow_dispatch:
name: Update Addons
jobs:
  update-addons:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          submodules: true
          fetch-depth: 0
      - run: |
          git submodule update --remote --merge --force repo/plugin.video.haru
          python3 _repo_generator.py
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: update addons"
